[burn-my-windows-profile]
pixel-wipe-enable-effect=false
tv-enable-effect=false
team-rocket-enable-effect=false
energize-b-enable-effect=false
matrix-enable-effect=false
tv-glitch-enable-effect=false
portal-enable-effect=false
trex-enable-effect=false
aura-glow-enable-effect=false
incinerate-enable-effect=false
fire-enable-effect=false
focus-enable-effect=false
apparition-enable-effect=false
broken-glass-enable-effect=false
doom-enable-effect=false
energize-a-enable-effect=false
paint-brush-enable-effect=false
snap-enable-effect=false
wisps-enable-effect=false
glide-enable-effect=true
mushroom-enable-effect=false
pixel-wheel-enable-effect=false
hexagon-enable-effect=false
rgbwarp-enable-effect=false
pixelate-enable-effect=false
glitch-enable-effect=false
glide-animation-time=190
glide-scale=0.96999999999999997
glide-squish=0.070000000000000007
glide-tilt=-0.059999999999999998
glide-shift=-0.02
